#Projeto Final
CREATE DATABASE DELIVERY_CANTINA;

USE DELIVERY_CANTINA;

CREATE TABLE PRODUTO(
COD_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO VARCHAR(40) NOT NULL,
DESCRICAO_PRODUTO VARCHAR(80) NOT NULL,
PRECO_PRODUTO NUMERIC(9,2) NOT NULL
);

INSERT INTO PRODUTO(NOME_PRODUTO,DESCRICAO_PRODUTO,PRECO_PRODUTO)
VALUES
('PASTA','ESPAGUETE BOLONHESA',11.99),
('PASTA','NHOQUE',14.99),
('PASTA','PENNE BOLONHESA',12.99),
('PASTA','RAVIOLI DE CARNE',15.99),
('PASTA','FETUTINE',13.99),
('PASTA','CAPELETI DE CARNE',15.99),
('HAMBURGUER','X-TUDO', 14.50),
('HAMBURGUER','TOP ESPECIAL', 18.50),
('HAMBURGUER','X-BACON', 11.50),
('HAMBURGUER','TRIPLO X', 21.50),
('PIZZA','PORTUGUESA MEDIA', 18.50),
('PIZZA','CALABREZA MEDIA', 19.00),
('PIZZA','MISTA MEDIA', 20),
('PIZZA','DA CASA MEDIA', 17.50),
('PIZZA','FRANGO COM BACON GRANDE', 22.50),
('PIZZA','MUSSARELA MEDIA', 24.50),
('PIZZA','FRANGO COM CATUPIRY GRANDE', 26.50),
('REFRIGERANTE','COCA-COLA', 3.50),
('REFRIGERANTE','CAFE', 2.50),
('REFRIGERANTE','MACA VERDE', 2.50),
('REFRIGERANTE','UVA', 2.50),
('REFRIGERANTE','LARANJA', 2.50),
('REFRIGERANTE','LIMAO', 2.50),
('SUCO','LARANJA GRANDE', 3.75),
('SUCO','COCO GRANDE', 3.75),
('SUCO','MORANGO GRANDE', 3.75),
('SUCO','MANGA MEDIA', 2.75),
('SUCO','UVA MEDIA', 2.75),
('SUCO','GRAVIOLA MEDIA', 2.75),
('SUCO','FRAMBOESA PEQUENO', 1.75),
('SUCO','LIMAO PEQUENO', 1.75),
('SUCO','MARACUJA PEQUENO', 1.75);

CREATE TABLE PEDIDO(
COD_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
NUM_PEDIDO INT NOT NULL,
PRAZO_ENTREGA TIME NOT NULL,
TAXA_ENTREGA NUMERIC(4,2) NOT NULL,
COD_PRODUTO INT NOT NULL,

CONSTRAINT FK_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);

INSERT INTO PEDIDO(NUM_PEDIDO,PRAZO_ENTREGA,TAXA_ENTREGA,COD_PRODUTO)
VALUES
(1,'00:30',2.00,3),
(1,'00:30',2.00,1),
(1,'00:30',2.00,11),
(1,'00:30',2.00,5),
(1,'00:30',2.00,7),
(1,'00:30',2.00,2),
(1,'00:30',2.00,14),
(1,'00:30',2.00,22);

CREATE TABLE ITEM_PEDIDO(
COD_ITEM_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
COD_PEDIDO INT NOT NULL,
COD_PRODUTO INT NOT NULL,
QTD_PEDIDO INT NOT NULL,

CONSTRAINT FK_PEDIDO_ITEM FOREIGN KEY(COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO),
CONSTRAINT FK_PRODUTO_ITEM FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);

INSERT INTO ITEM_PEDIDO 
VALUES
(1,1,3),
(2,2,2),
(5,11,4),
(8,7,11),
(6,9,6),
(7,22,4),
(4,17,2),
(9,18,1);

