CREATE DATABASE LETSFLIX;

USE LETSFLIX;

CREATE TABLE LETSFLIX_FILME(
COD_FILME INT PRIMARY KEY AUTO_INCREMENT,
NOME_FILME VARCHAR(80) NOT NULL,
AUTOR VARCHAR(40) NOT NULL,
DURACAO TIME NOT NULL,
BILHETERIA NUMERIC(9,2) NOT NULL,
NOTA VARCHAR(10) NOT NULL
);

CREATE TABLE LETSFLIX_GENERO(
COD_GENERO INT PRIMARY KEY AUTO_INCREMENT,
TIPO VARCHAR(40) NOT NULL,
CLASSIFICACAO VARCHAR(5) NOT NULL
);

INSERT INTO LETSFLIX_FILME(NOME_FILME,AUTOR,DURACAO,BILHETERIA,NOTA)
VALUES 
  ('Homem-Aranha','Michael','02:36:59',2.000000,'9.2'),
  ('Homem-Formiga','Gustavo','01:47:50',1.000000,'8.4'),
  ('Vingadores','Joao','01:40:00',500.000,'7.4');

INSERT INTO LETSFLIX_GENERO(TIPO,CLASSIFICACAO)
VALUES 
  ('Acao',16),
  ('Comedia',12),
  ('Terror', 18);
  
